-- Patch notes data structure - update this for each release
PATCH_NOTES = {
  {
    version = '1.2.9',
    date = '2025-11-14',
    notes = {
      'NEW FEATURES:',
      '• UHC Raid Frames',
      '',
      'NEW STATISTICS:',
      '• Map key presses while map blocked',
      '  • Tracks the number of times the map key has been pressed whilst blocked by the Route Planner Extreme option.',
      '',
      'UI IMPROVEMENTS:',
      '• Reset on screen statistics command: "/uhcrs" or "/uhcstatsreset"',
      '• Added an option to play a subtle audio cue upon reaching full health',
      '• Added one time Resource Tracking Explainer',
      '  • The addon will show a message on the screen explaining how to use the resource tracking feature when the minimap is hidden.',
      '',
      'BUG FIXES:',
      '• Fix: Route planner added to xp gained tracker',
      '',
      'OTHER:',
      '• Don`t send the join party message on non-Hardcore servers',
    },
  },
  {
    version = '1.2.8',
    date = '2025-11-04',
    notes = {
      'UI IMPROVEMENTS:',
      '• Add fstack name to route planner compass',
      '',
      'BUG FIXES:',
      '• Fix action bar visibility after taxi',
      '• Fix tracking map overlay showing party members etc',
      '',
      'OTHER:',
      '• Remove Trade Restrictions',
      '• Remove Cancel Buffs',
    },
  },
  {
    version = '1.2.7',
    date = '2025-11-03',
    notes = {
      'NEW FEATURES:',
      '• Reject buffs from others (experimental option)',
      '  • When enabled, the addon will reject buffs from other players.',
      '• Route planner now hides player position markers on the map.',
      '• Added buttons for invite to party and leave group',
      '  • These buttons will be displayed in the bottom right corner of the screen.',
      '  • Only show when the "Completely Remove Player Frame" and "Completely Remove Target Frame" are enabled.',
      '• Minimap Clock',
      '  • Added a clock to the top right corner of the screen.',
      '  • Added a scaling slider to update the size of the clock.',
      '• Added resource bar colour picker.',
      '  • Allows you to change the colour of the resource and pet resource bars.',
      '• Added statistics background opacity slider.',
      '  • Allows you to change the opacity of the on screen statistics background.',
      '',
      'NEW STATISTICS:',
      '• Mana potions used.',
      '• Max heal crit value.',
      '• Duels total.',
      '• Duels won.',
      '• Duels lost.',
      '• Duels win percentage.',
      '• Player jumps.',
      '',
      'UI IMPROVEMENTS:',
      '• Add collapseable sections to the settings menu.',
      '• Show selection count on each option section header.',
      '• Escape key now closes the settings menu.',
      '• Tooltips show grey if you will receive no xp for killing the unit.',
      '• Buffs on resource bar positioning improved for combo point characters.',
      '',
      'BUG FIXES:',
      '• Fix: Tunnel vision fails when reapplied within 0.6s.',
      '• Fix: Moonkin and dire bear form resource bar default colours.',
      '',
      'OTHER:',
      '• Removed halloween holiday updates from default settings',
    },
  },{
    version = '1.2.6',
    date = '2025-10-22',
    notes = {
      'NEW FEATURES:',
      '• Added Tunnel Vision Covers Everything to ULTRA preset settings',
      '• Added Super Spooky Tunnel Vision',
      '  • When enabled, the tunnel vision will be displayed in a spooky Halloween theme.',
      '• Added Terrifying Pumpkin Themed Settings Presets',
      '• Added Highest Crit Appreciation Soundbite',
      '  • Play a soundbite when you achieve a new highest crit value',
    '• Added Party Death Soundbite',
    '  • Play a soundbite when a party member dies',
    '• Added Player Death Soundbite',
    '  • Play a soundbite when you die',
    '• Added "Completely Remove Target Frame" to EXPERIMENTAL settings',
    '  • When enabled, the target frame will be completely removed from the screen.',
    '• Added "Completely Remove Player Frame" to EXPERIMENTAL settings',
    '  • When enabled, the player frame will be completely removed from the screen.',
    '• Added Tooltips to Statistics labels',
    '  • When you hover over a statistic label, a tooltip will be displayed with the statistic description.',
    '• Added Slash command to set lowest health',
    '  • /setlowesthealth <value> (e.g. /setlowesthealth 20)',
    '  • <value> is a number between 0 and 100',
    '  • This command will only set the value if it is higher than the current lowest health.',
    '',
    'BUG FIXES:',
    '• Fix bug where buffs are uncancellable in combat.',
    '• Fix: Allow Hidden Action Bars to show Action Bars when on a taxi.',
    '• Fix nameplates issue causing guild promo break. (wtf?)',
    '• Fix Dueling lowest health level & session tracking issue.',
    '• Fix: Missing Sound files from zip upload.',
    '• Fix: Missing Libs from zip upload.',
    '',
    'TECHNICAL IMPROVEMENTS:',
    '• Massive codebase cleanup.',
  },
}, {
  version = '1.2.5',
  date = '2025-10-21',
  notes = { '• Auto run save resource bar position if the value is not set.' },
}, {
  version = '1.2.4',
  date = '2025-10-21',
  notes = {
    '• Added Slash command to reset resource bar position',
    '  • /resetresourcebar or /rrb',
  },
}, {
  version = '1.2.3',
  date = '2025-10-20',
  notes = {
    '• Added Patch notes and version update dialog',
    '  • Each time you update the addon, you will see this dialog with the patch notes.',
    '• On screen statistics are toggleable in settings menu.',
    '  • Each player can decide which statistics they want to see on screen.',
    '• Pet resource bar attached to custom resource bar.',
    '• Ultra options in settings menu',
    '  • Pets die permanently when killed.',
    '  • Hide Actions bars when not resting or under Cozy Fire.',
    '  • These settings have been moved from the Experimental section.',
    '• Misc options in settings menu',
    '  • Several options in the addon have been moved to the misc section.',
    "  • These settings do not belong in any 'difficult' section.",
    '• Misc options do not show in XP Gained tracking',
    "  • These settings have nothing to do with the 'difficulty' of the addon, and so are not tracked for XP gained without them.",
    '• Announce ULTRA player info on join party (misc option)',
    '  • Dungeons completed.',
    '  • Party member deaths.',
    '  • Both, either or non of these options can be enabled.',
    '• Buffs & Debuffs on resource bar (misc option)',
    '  • When enabled, buffs and debuffs will be displayed above and below the custom resource bar.',
    '• Fixed player name right click issues.',
    '  • Whisper tab would not update after leaving the tab.',
    '  • Report player would not work properly.',
    '  • Copy player name would not copy to clipboard.',
    '• Added New Statistics:',
    '  • Close Escapes statistic',
    '  • Highest Crit statistic',
    '  • Dungeon Bosses Killed statistic',
    '  • Dungeons Completed statistic',
    '  • Rare Elites Slain statistic',
    '  • World Bosses Slain statistic',
    '  • Party Deaths Witnessed statistic',
    '• Fixed LFG search error.',
  },
} }
