-- Patch notes data structure - update this for each release
PATCH_NOTES = { {
  version = '1.2.6',
  date = '2025-10-22',
  notes = {
    '• Added Super Spooky Tunnel Vision',
    '  • When enabled, the tunnel vision will be displayed in a spooky Halloween theme.',
    '• Added Terrifying Pumpkin Themed Settings Presets',
    '• Added Highest Crit Appreciation Soundbite',
    '  • Play a soundbite when you achieve a new highest crit value',
    '• Added Party Death Soundbite',
    '  • Play a soundbite when a party member dies',
    '• Added Player Death Soundbite',
    '  • Play a soundbite when you die',
  },
}, {
  version = '1.2.5',
  date = '2025-10-21',
  notes = { '• Auto run save resource bar position if the value is not set.' },
}, {
  version = '1.2.4',
  date = '2025-10-21',
  notes = {
    '• Added Slash command to reset resource bar position',
    '  • /resetresourcebar or /rrb',
  },
}, {
  version = '1.2.3',
  date = '2025-10-20',
  notes = {
    '• Added Patch notes and version update dialog',
    '  • Each time you update the addon, you will see this dialog with the patch notes.',
    '• On screen statistics are toggleable in settings menu.',
    '  • Each player can decide which statistics they want to see on screen.',
    '• Pet resource bar attached to custom resource bar.',
    '• Ultra options in settings menu',
    '  • Pets die permanently when killed.',
    '  • Hide Actions bars when not resting or under Cozy Fire.',
    '  • These settings have been moved from the Experimental section.',
    '• Misc options in settings menu',
    '  • Several options in the addon have been moved to the misc section.',
    "  • These settings do not belong in any 'difficult' section.",
    '• Misc options do not show in XP Gained tracking',
    "  • These settings have nothing to do with the 'difficulty' of the addon, and so are not tracked for XP gained without them.",
    '• Announce ULTRA player info on join party (misc option)',
    '  • Dungeons completed.',
    '  • Party member deaths.',
    '  • Both, either or non of these options can be enabled.',
    '• Buffs & Debuffs on resource bar (misc option)',
    '  • When enabled, buffs and debuffs will be displayed above and below the custom resource bar.',
    '• Fixed player name right click issues.',
    '  • Whisper tab would not update after leaving the tab.',
    '  • Report player would not work properly.',
    '  • Copy player name would not copy to clipboard.',
    '• Added New Statistics:',
    '  • Close Escapes statistic',
    '  • Highest Crit statistic',
    '  • Dungeon Bosses Killed statistic',
    '  • Dungeons Completed statistic',
    '  • Rare Elites Slain statistic',
    '  • World Bosses Slain statistic',
    '  • Party Deaths Witnessed statistic',
    '• Fixed LFG search error.',
  },
} }
